import * as monaco from 'monaco-editor'

export const languages =
{
    'Python3':{
      desc: "Easy, versatile, general-purpose interpreter",
      highlighting:"python",
      ext: 'py',
      kor: '파이썬3',
      template:"python",
      icon:'mdi-language-python',
      command:"python3 {ARGS} {FILENAME}.{EXT}",
      cli: 'python3 {ARGS}',
      errorRegEx: ".+?\\.py\", line (\\d+)(?:.*?\r\n)+?(.*?Error: .*)",
      keyBindings: monaco.KeyMod.chord(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_M, monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_P),
      dockerImage: "ryusatgat/python",
      homepage: 'https://www.python.org',
      repo: 'https://github.com/python',
    },
    'Javascript (Node.js)':{
      desc: "JavaScript runtime, event-driven, and non-blocking",
      highlighting:"javascript1",
      ext: 'js',
      kor: '자바스크립트 (노드.js)',
      template:"javascript",
      icon:'mdi-nodejs',
      command:"node {ARGS} {FILENAME}.{EXT}",
      cli: 'node {ARGS}',
      errorRegEx: ".+:(\\d+)\r\n.+\r\n.+\r\n\r\n(.+)\r\n",
      keyBindings: monaco.KeyMod.chord(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_M, monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_J),
      dockerImage: "ryusatgat/base",
      homepage: 'https://nodejs.org',
      repo: 'https://github.com/nodejs',
    },
    'TypeScript':{
      desc: "JavaScript with static types and tooling",
      highlighting:"typescript1",
      ext: 'ts',
      kor: '타입스크립트',
      template:"typescript",
      icon:'mdi-language-typescript',
      args: "--pretty false --target es2015",
      command:"tsc {ARGS} {FILENAME}.{EXT} && node {FILENAME}.js",
      cli: 'ts-node',
      errorRegEx: ".+?\\((\\d+),\\d+\\): (.+)",
      keyBindings: monaco.KeyMod.chord(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_M, monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_T),
      dockerImage: "ryusatgat/base",
      homepage: 'https://www.typescriptlang.org',
      repo: 'https://github.com/microsoft/TypeScript',
    },
    'Java (OpenJDK)':{
      desc: "Object-oriented, high-performance, and cross-platform",
      highlighting:"java",
      ext: 'java',
      kor: '자바',
      template:"java",
      icon:'mdi-language-java',
      command:"javac {ARGS} {FILENAME}.{EXT} && java {FILENAME}",
      cli: 'jshell',
      defaultFilename: 'Main',
      errorRegEx: ".+?:(\\d+): (\\w+: .+)",
      keyBindings: monaco.KeyMod.chord(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_M, monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_V),
      dockerImage: "ryusatgat/jvm",
      homepage: 'https://openjdk.org',
      repo: 'https://github.com/openjdk',
    },
    'C (gcc)':{
      desc: "Low-level, efficient, and fast compiler",
      highlighting:"c",
      ext: 'c',
      kor: 'C언어 - gcc',
      template:"c",
      icon:'mdi-language-c',
      args: '-Wall -lm -lcrypto',
      command:"gcc -fdiagnostics-color=never -o {FILENAME} {FILENAME}.{EXT} {ARGS} && ./{FILENAME}",
      cli: null,
      errorRegEx: ".+?\\.c:(\\d+):\\d+: error: (.*)",
      keyBindings: monaco.KeyMod.chord(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_M, monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_C),
      dockerImage: "ryusatgat/base",
      homepage: 'https://gcc.gnu.org',
      repo: 'https://gcc.gnu.org/git.html',
    },
    'C++ (g++)':{
      desc: "Object-oriented, high-performance, versatile, compiled, complex",
      highlighting:"cpp",
      ext: 'cc',
      kor: 'C++ - g++',
      template:"cc",
      icon:'mdi-language-cpp',
      args: '-Wall -lboost_system -lboost_thread -pthread -ltbb',
      command:"g++ -fdiagnostics-color=never -o {FILENAME} {FILENAME}.{EXT} {ARGS} && ./{FILENAME}",
      cli: null,
      errorRegEx: ".+?\\.cc:(\\d+):\\d+: error: (.*)",
      keyBindings: null,
      dockerImage: "ryusatgat/base",
      homepage: 'https://gcc.gnu.org',
      repo: 'https://gcc.gnu.org/git.html',
    },
    'Go':{
      desc: "Concurrent, statically-typed, systems language",
      highlighting:"go",
      ext: 'go',
      kor: '고',
      template:"go",
      icon:'mdi-language-go',
      command:"go build {ARGS} {FILENAME}.{EXT} && ./{FILENAME}",
      cli: null,
      errorRegEx: ".+:(\\d+):\\d+: (.*)",
      keyBindings: monaco.KeyMod.chord(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_M, monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_G),
      dockerImage: "ryusatgat/go",
      homepage: 'https://go.dev',
      repo: 'https://github.com/golang/go',
    },
    'Rust':{
      desc: "Systems, safe, concurrent, performant, modern",
      highlighting:"rust",
      ext: 'rs',
      kor: '러스트',
      template:"rust",
      icon:'mdi-language-rust',
      command:"rustc {ARGS} {FILENAME}.{EXT} && ./{FILENAME}",
      cli: null,
      errorRegEx: ".+?: .+?\r\n.+?:(\\d+):(.*)",
      keyBindings: null,
      dockerImage: "ryusatgat/rust",
      homepage: 'https://www.rust-lang.org',
      repo: 'https://github.com/rust-lang/rust',
    },
    'Ruby':{
      desc: "Dynamic, object-oriented, expressive language",
      highlighting:"ruby",
      ext: 'rb',
      kor: '루비',
      template:"ruby",
      icon:'mdi-language-ruby',
      command:"ruby {ARGS} {FILENAME}.{EXT}",
      cli: "irb",
      errorRegEx: ".+?\\.rb:(\\d+): (.*)",
      keyBindings: null,
      dockerImage: "ryusatgat/ruby",
      homepage: 'https://www.ruby-lang.org',
      repo: 'https://github.com/ruby/ruby',
    },
    'PHP':{
      desc: "Server-side web scripting tool",
      highlighting:"php",
      ext: 'php',
      kor: 'PHP',
      template:"php",
      icon:'mdi-language-php',
      args: '-q',
      command:'php-cgi {ARGS} {FILENAME}.{EXT} > {FILENAME}.html && imshow {FILENAME}.html',
      cli: null,
      errorRegEx: "PHP \\w+ error:  .*?(\\d+)(\r\n)",
      keyBindings: null,
      dockerImage: "ryusatgat/base",
      homepage: 'https://www.php.net',
      repo: 'https://github.com/php/php-src',
    },
    'Swift':{
      desc: "Safe, modern, fast, general-purpose",
      highlighting:"swift",
      ext: 'swift',
      kor: '스위프트',
      template:"swift",
      icon:'mdi-language-swift',
      args: '-no-color-diagnostics',
      command:"swift {ARGS} {FILENAME}.{EXT}",
      cli: null,
      errorRegEx: ".*:(\\d+):\\d+: (.*)",
      keyBindings: null,
      dockerImage: "ryusatgat/swift",
      homepage: 'https://developer.apple.com/kr/swift',
      repo: 'https://github.com/swiftlang/swift',
    },
    'Kotlin':{
      desc: "Modern, Statically-typed, JVM-compatible, Concise, Interoperable",
      highlighting:"kotlin",
      ext: 'kt',
      kor: '코틀린',
      template:"kotlin",
      icon:'mdi-language-kotlin',
      args: '-include-runtime',
      command:"kotlinc {FILENAME}.{EXT} {ARGS} -d {FILENAME}.jar && java -jar {FILENAME}.jar",
      cli: "kotlin",
      errorRegEx: ".+?:(\\d+):\\d+: .+: (.*)",
      keyBindings: monaco.KeyMod.chord(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_M, monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_K),
      dockerImage: "ryusatgat/jvm",
      homepage: 'https://kotlinlang.org',
      repo: 'https://github.com/JetBrains/kotlin',
    },
    'C# - .NET Core':{
      desc: "Cross-platform .NET runtime environment",
      highlighting:"csharp",
      ext: 'cs',
      kor: 'C샵 - 닷넷 코어',
      template:"csharp",
      icon:'mdi-language-csharp',
      command:"([ -d {FILENAME}_Dotnet ] || dotnet new console -o {FILENAME}_Dotnet) && mv -f {FILENAME}.{EXT} {FILENAME}_Dotnet/Program.{EXT} && dotnet run {ARGS} --project {FILENAME}_Dotnet",
      cli: null,
      defaultFilename: 'Main',
      errorRegEx: ".+?\\((\\d+),\\d+\\): error .+?: (.+)",
      keyBindings: null,
      dockerImage: "ryusatgat/ms",
      homepage: 'https://dotnet.microsoft.com/en-us/languages/csharp',
      repo: 'https://github.com/dotnet/csharplang',
    },
    'Bash':{
      desc: "Shell scripting, command-line, and Unix-based",
      highlighting:"shell",
      ext: 'sh',
      kor: '리눅스 셸',
      template:"bash",
      icon:'mdi-bash',
      command:"chmod 755 {FILENAME}.{EXT} && bash {ARGS} ./{FILENAME}.{EXT}",
      cli: null,
      errorRegEx: ".*\\.sh: .+? (\\d+): (.*)",
      keyBindings: monaco.KeyMod.chord(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_M, monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_L),
      dockerImage: "ryusatgat/base",
      homepage: 'https://www.gnu.org/software/bash',
      repo: 'https://git.savannah.gnu.org/cgit/bash.git',
    },
    'R':{
      desc: "Statistical computing, data analysis language",
      highlighting:"r",
      ext: 'R',
      template:"r",
      kor: 'R',
      icon:'mdi-language-r',
      command:"R {ARGS} --slave -q -f {FILENAME}.{EXT}",
      cli: 'R',
      keyBindings: monaco.KeyMod.chord(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_M, monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_R),
      dockerImage: "ryusatgat/base",
      homepage: 'https://www.r-project.org',
      repo: 'https://cran.r-project.org/mirrors.html',
    },
}
